LOCALIZATION_TOKEN="PLACEHOLDER_KEY"

DEBUG_STORE_FILE="PLACEHOLDER_KEY"
DEBUG_STORE_PASSWORD="PLACEHOLDER_KEY"
DEBUG_KEY_PASSWORD="PLACEHOLDER_KEY"
DEBUG_KEY_ALIAS="PLACEHOLDER_KEY"

PROD_STORE_FILE="PLACEHOLDER_KEY"
PROD_STORE_PASSWORD="PLACEHOLDER_KEY"
PROD_KEY_PASSWORD="PLACEHOLDER_KEY"
PROD_KEY_ALIAS="PLACEHOLDER_KEY"
