[versions]
versionName = "0.3.4"
versionCode = "1"
namespace = "hu.kocsisgeri.betterneptun"

minSdk = "31"
compileSdk = "37"
targetSdk = "36"
javaVersion = "11"

localizationSnapshot = "snapshot_2026-06-16_19-42-57_911_d1ed36b5"