[versions]
versionName = "0.3.4"
versionCode = "1"
namespace = "hu.kocsisgeri.betterneptun"

minSdk = "31"
compileSdk = "37"
targetSdk = "36"
javaVersion = "11"

localizationSnapshot = "snapshot_2026-06-06_23-28-04_108_82ab7305"